// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfEwP2rAOrTx7Ea6hquvKZrunW7pD6nZ8',
    appId: '1:394964116604:web:bea2af972b079fdb4a15f9',
    messagingSenderId: '394964116604',
    projectId: 'fir-memo-app-a9982',
    authDomain: 'fir-memo-app-a9982.firebaseapp.com',
    storageBucket: 'fir-memo-app-a9982.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0G8DXMwUn573ol1SP3i6tdV5ELZ-3BYo',
    appId: '1:394964116604:android:b0276e9e71cb046e4a15f9',
    messagingSenderId: '394964116604',
    projectId: 'fir-memo-app-a9982',
    storageBucket: 'fir-memo-app-a9982.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtoywOfP0SFcsZ5jJXnwRDbQUSEmGwnuY',
    appId: '1:394964116604:ios:2c7b7ee456294e194a15f9',
    messagingSenderId: '394964116604',
    projectId: 'fir-memo-app-a9982',
    storageBucket: 'fir-memo-app-a9982.firebasestorage.app',
    iosBundleId: 'com.example.memoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtoywOfP0SFcsZ5jJXnwRDbQUSEmGwnuY',
    appId: '1:394964116604:ios:2c7b7ee456294e194a15f9',
    messagingSenderId: '394964116604',
    projectId: 'fir-memo-app-a9982',
    storageBucket: 'fir-memo-app-a9982.firebasestorage.app',
    iosBundleId: 'com.example.memoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfEwP2rAOrTx7Ea6hquvKZrunW7pD6nZ8',
    appId: '1:394964116604:web:9f961460dcdd8cff4a15f9',
    messagingSenderId: '394964116604',
    projectId: 'fir-memo-app-a9982',
    authDomain: 'fir-memo-app-a9982.firebaseapp.com',
    storageBucket: 'fir-memo-app-a9982.firebasestorage.app',
  );
}